### ISSUE TITLE
[EPIC]: Configurable Control Schemes

### ISSUE THREAD

**Issue by HexaField** [EtherealEngine/etherealengine#5182]
The user should be able to easily switch between multiple control schemes suited to different devices. This will be located in the 'settings' menu which can be opened second from the left at the bottom of the screen. We should also be able to specify the default per-scene.

Desktop
- [x] WASD/Arrow keys + Mouse drag to look
- [ ] WASD/Arrow keys + Pointer lock https://github.com/XRFoundation/XREngine/issues/3108
- [ ] navmesh click to move

Mobile
- [x] gamepad move + touch drag look
- [ ] gamepad move + gamepad look
- [ ] navmesh tap to move

VR
- [x] thumbstick look + thumbstick move
- [x] thumbstick look + teleport move https://github.com/XRFoundation/XREngine/issues/5063
