### ISSUE TITLE
[Epic] Unit tests for all server-core services

### ISSUE THREAD

**Issue by HexaField** [EtherealEngine/etherealengine#5997]
- [ ] analytics
- [ ] analytics-setting
- [ ] asset-library
- [ ] authManagement
- [ ] authentication
- [ ] authentication-setting
- [ ] avatar
- [ ] aws-setting
- [ ] bot
- [ ] bot-command
- [ ] channel
- [ ] channel-type
- [ ] chargebee-setting
- [ ] client-setting
- [ ] discord-bot-auth
- [ ] email
- [ ] email-setting
- [x] file-browser
- [ ] file-browser/upload
- [ ] game-server-setting
- [ ] gameserver-load
- [ ] gameserver-provision
- [ ] gameserver-subdomain-provision
- [ ] github-app
- [ ] group
- [ ] group-user
- [ ] group-user-rank
- [x] identity-provider
- [x] instance
- [ ] instance-attendance
- [ ] instance-authorized-user
- [ ] instance-provision
- [x] invite
- [ ] invite-type
- [ ] location
- [ ] location-admin
- [ ] location-ban
- [ ] location-settings
- [ ] location-type
- [ ] login
- [ ] login-token
- [ ] magic-link
- [ ] match-instance
- [ ] match-ticket
- [ ] match-ticket-assignment
- [ ] match-user
- [ ] message
- [ ] message-status
- [ ] party
- [ ] party-user
- [ ] portal
- [ ] project
- [ ] project-build
- [ ] project-invalidate
- [ ] project-setting
- [ ] redis-setting
- [ ] route
- [ ] route-activate
- [ ] routes-installed
- [ ] rtc-ports
- [x] #7740
- [x] scenes
- [ ] scope
- [ ] scope-type
- [ ] server-setting
- [ ] sms
- [ ] static-resource
- [ ] static-resource-type
- [ ] testbot
- [ ] upload-asset
- [x] user
- [ ] user-api-key
- [ ] user-relationship
- [ ] user-relationship-type
- [ ] user-role
- [ ] user-settings
- [ ] visualisation
