### ISSUE TITLE
[EPIC]: Avatar Pipeline

### ISSUE THREAD

**Issue by HexaField** [EtherealEngine/etherealengine#6314]
- [ ] https://github.com/XRFoundation/XREngine/issues/5826
- [x] https://github.com/XRFoundation/XREngine/issues/5831
- [ ] https://github.com/XRFoundation/XREngine/issues/5895
- [ ] https://github.com/XRFoundation/XREngine/issues/5894
- [x] https://github.com/XRFoundation/XREngine/issues/5831
- [ ] https://github.com/XRFoundation/XREngine/issues/5781
- [x] https://github.com/XRFoundation/XREngine/issues/5180
- [x] https://github.com/XRFoundation/XREngine/issues/5831
