### ISSUE TITLE
[EPIC]: Navmesh, Autopilot & Maps

### ISSUE THREAD

**Issue by HexaField** [EtherealEngine/etherealengine#6315]
- [ ] https://github.com/XRFoundation/XREngine/issues/3811
- [ ] https://github.com/XRFoundation/XREngine/issues/5682
- [ ] https://github.com/XRFoundation/XREngine/issues/5266
- [ ] https://github.com/XRFoundation/XREngine/issues/5682
