### ISSUE TITLE
[Epic] ECS Recording & Playback Streaming

### ISSUE THREAD

**Issue by HexaField** [EtherealEngine/etherealengine#6711]
- [x] #7761
- [ ] FFMPEG, gstream & mediasoup write to disk
- [ ] upload file to s3
- [ ] stream file back to instance server

Mediasoup to > ffmpeg > static-resources/s3
https://github.com/versatica/mediasoup-demo/blob/v3/broadcasters/ffmpeg.sh

AWS has stream stuff for node
https://dev.to/about14sheep/streaming-data-from-aws-s3-using-nodejs-stream-api-and-typescript-3dj0

https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Recording_API to local too?
