### ISSUE TITLE
[Epic]: XR CV Fixed Camera Mode

### ISSUE THREAD

**Issue by mrhegemon** [EtherealEngine/etherealengine#7235]
## Dependent on

- [ ] https://github.com/XRFoundation/XREngine/issues/5644
- [ ] https://github.com/XRFoundation/XREngine/issues/5303

## Stories

- [ ] Create Static Mode for sitting standing in front of a CV camera for mocap or AR magic window
