### ISSUE TITLE
[EPIC] Generalized asset optimization pipeline

### ISSUE THREAD

**Issue by HexaField** [EtherealEngine/etherealengine#7464]
Blocked by 
- [x] static resources 
- [x] Feathers service for optimizing assets
Optimization pipeline should be configurable per asset
Source assets should compile to a matrix of optimized destination assets
- [ ] Source Asset LODs 0 1 2 3
   - Level 0 is highest quality
   - Each LOD should be a different glb, with less geometry and texture size as levels increase
   - Can we generate these LODs automatically from level 0 if the source asset does not include multiple LODs? 
- [x] KTX2 configurable per texture
   - Default ETC1S - UASTC should be an option for text images
   - Setting for normal maps
- [x]  Draco compression configurable for each asset (or LOD? Or geometry?)
- [ ]  Tool tips in studio!
Source assets should remain untouched as the source of truth!
   - Whenever source assets are modified, they should trigger destination assets to be compiled
 - [x] Refactor/streamline feathers service: [CMS EE](https://docs.google.com/drawings/d/1IAIeHEaKlLC9RGu9YNA4KZBThbC_Czv6cjnzfLHDf-A/edit)
- [ ] Helper functions for querying, adding, removing content
- [x] LOD system within static resources
- [x] #7819
- [ ] #8230 
- [ ] #8183

**Comment by dinomut1** [comment]
this stuff is covered in other more recent issues
