### ISSUE TITLE
[Epic] VRM - Rebuild Avatar Source Rig

### ISSUE THREAD

**Issue by HexaField** [EtherealEngine/etherealengine#7592]
- [x] Migrate base rig to VRM
- [x] Separate animations from retargeting source rig
- [x] Pull animations out into packs
- [x] FK & IK Blending
- [ ] Better hint estimation heuristics
- [ ] Add back all emote animations
- [ ] Optimization pass
- [ ] Double check WebXR wrist rotation & wrist offset
- [ ] Ensure ee-development-test-suite examples are passing

https://vrm-addon-for-blender.info/en/create-humanoid-vrm-from-scratch/
https://styly.cc/tips/blender-modeling-vrm/
https://styly.cc/tips/unity-fbx2vrm/
https://www.youtube.com/watch?v=i2pOourRdFU
