### ISSUE TITLE
[EPIC] Upgrade to feathers 5.0.0

### ISSUE THREAD

**Issue by speigg** [EtherealEngine/etherealengine#7645]
https://github.com/feathersjs/feathers/releases/tag/v5.0.0

- [x] Upgrade all packages to 5.0.0. Test current code base.
- [x] Removed unused hooks
- [x] #7726
- [x] https://github.com/EtherealEngine/etherealengine/issues/7802 https://feathersjs.com/api/koa.html
- [x] #8871
- [x] Create migrations to ensure tables creation and ensure seeders work fine.
- [x] Checklist of database based services:
  - [x] analytics
  - [x] authentication-setting
  - [x] avatar
  - [x] aws-setting
  - [x] bot #8573
  - [x] bot-command
  - [x] build-status
  - [x] channel #8665
  - [x] channel-user #8481 
  - [x] chargebee-setting
  - [x] client-setting
  - [x] coil-setting
  - [x] email-setting
  - [x] github-repo-access #8286
  - [x] helm-setting
  - [x] identity-provider #8423
  - [x] instance #8615
  - [x] instance-server-setting
  - [x] instance-attendance #8399
  - [x] instance-authorized-user #8400
  - [x] invite #8497
  - [x] invite-type #8421
  - [x] location #8284
  - [x] location-settings #8284
  - [x] location-type #8284
  - [x] location-admin #8392
  - [x] location-authorized-user #8386
  - [x] location-ban #8381
  - [x] login-token #8452
  - [x] match-instance
  - [x] match-user
  - [x] message #8572
  - [x] project #8507 
  - [x] project-permission-type #8363
  - [x] project-permission #8456
  - [x] recording #8424
  - [x] recording-resource #8410
  - [x] redis-setting
  - [x] route
  - [x] scope #8480
  - [x] scope-type #8299
  - [x] server-setting
  - [x] static_resource #8457
  - [x] task-server-setting
  - [x] user #8368
  - [x] user-api-key #8338
  - [x] user-kick #8446
  - [x] user-relationship #8447
  - [x] user-relationship-type #8448
  - [x] user-setting #8449
- [x] Checklist of non-database based services:
  - [x] accept-invite #8663
  - [x] asset-library #8680
  - [x] auth-management #8683
  - [x] email #8684
  - [x] file-browser #8737
  - [x] instance-provision #8765
  - [x] login #8701
  - [x] magic-link #8724
  - [x] model-transform #8729
  - [x] project-setting #8742
  - [x] scene #8743
  - [x] server-info #8739
  - [x] server-logs #8740
  - [x] shopify-cart #8744
  - [x] sms #8747
  - [x] verification-event #8749
- [x] dev-reinit should also clear data from tables that do not have seed files.

Issues Found in Feathers Typing:
- When querying `find` from client, if we pass pagination as false then it returns data in array. But if we pass pagination as undefined, then data is always retured as Paginated object though return typings show it to be either Paginated object or Array. Therefore, we have to explicitly parse the result to Paginated object.
- When querying `find` from client, if we pass pagination as false then it returns data in array. We have to first convert that response to any and then to Array.
- In `authentication-setting` service when we override `patch` method we have to convert object to strings before passing to `super._patch` method. Though as per typings, `super._patch` method expects them to be object.

**Comment by HexaField** [comment]
https://cdn.discordapp.com/attachments/1082866280354291712/1120310420603932713/etherealengine.png
