### ISSUE TITLE
[Epic]: Add OpenSaerch to the Cluster for many Analytics and Search Functions

### ISSUE THREAD

**Issue by mrhegemon** [EtherealEngine/etherealengine#7774]
## Dependent on

- [ ] Getting MoCap done
- [ ] Adding Metadata to Scens
- [ ] Adding Metadata to Static Resources

## Stories

- [ ] Send tons of logs and data streams to Open Search, 2D, text, 3D, geodata/AR
- [ ] Send mocap frames to OpenSearch - Frame, body, object tracking schema
- [ ] Full-text search Static Resources
- [ ] Full-text search Scenes
- [ ] Make some pre-canned DSL searches
- [ ] Add Vector Search for crazy machine learning stuff - https://opensearch.org/docs/latest/search-plugins/neural-search/

Make it run on K8s -
