### ISSUE TITLE
[Epic] WebGPU Advanced Pipeline Features

### ISSUE THREAD

**Issue by HexaField** [EtherealEngine/etherealengine#8557]
- [ ] WebGPU supports PBR materials
- [ ] https://github.com/EtherealEngine/etherealengine/issues/7943
- [ ] WebGPU Ray Tracing
- [ ] https://github.com/EtherealEngine/etherealengine/issues/7879
- [ ] WebGPU Oculus Multiview
- [ ] WebGPU Space Warp

**Comment by HexaField** [comment]
moved to https://github.com/EtherealEngine/etherealengine/issues/5489
