### ISSUE TITLE
[Epic]: Ethereal Engine Monitoring and Logging Integration

### ISSUE THREAD

**Issue by Griffisaurus** [EtherealEngine/etherealengine#8636]
We need to integrate it into the engine, our development, and DevOps workflow.  The tasks for this are:

- [ ]  Set up a separate kubernetes cluster dedicated to logging and monitoring using Open Search.
- [ ] Ensure our Open Search implementation has access to all of Ethereal Engine and monitors all deployments (currently dev, app, exp)
- [ ] Add additional logs and log levels to cover all levels of Ethereal Engine (information to come)
- [ ] Build a native Open Search dashboard
- [ ] Link Open Search to the appropriate Ethereal Engine deployment's admin panel and surface hot statistics like instance health, crashes, etc. that will display in a new area of admin panel https://www.flaticon.com/free-icon/log_1960242?term=logging&page=1&position=1&origin=tag&related_id=1960242
- [ ]  Revamp the user analytics portion of the admin panel to surface user relevant KPIs
      - [ ] new users
      - [ ] active users within the last 15, 30 days
      - [ ] average user time spent for different locations
      - [ ] number of page views by users with accounts and guests
      - [ ] Unique Visitors
      - [ ] Session Duration

- [ ] https://github.com/EtherealEngine/etherealengine/issues/7221
- [ ] https://github.com/EtherealEngine/etherealengine-control-center/issues/69
- [ ]

**Comment by ashish-aesthisia** [comment]
Sure I am starting on this, we might need to discuss more on 
Revamp the user analytics portion of the admin panel to surface user relevant KPIs

**Comment by HexaField** [comment]
merged with https://github.com/EtherealEngine/etherealengine/issues/7774
