### ISSUE TITLE
[Epic] New Scene Format

### ISSUE THREAD

**Issue by HexaField** [EtherealEngine/etherealengine#8761]
- [ ] Migrate Scene JSON to GLTF
- [ ] https://github.com/EtherealEngine/etherealengine/issues/8496
- [ ] Support partials/delta files akin to USDZ layers
- [ ] Snapshots via event sourcing deserialize GLTF to ECS
- [ ] https://github.com/EtherealEngine/etherealengine/issues/6951
- [ ]
