### ISSUE TITLE
[Epic]: Kit Pieces, Object Space Snapping

### ISSUE THREAD

**Issue by dinomut1** [EtherealEngine/etherealengine#9175]
We want to create a kit system which allows easily building virtual spaces with modular building blocks. These building blocks should
- share textures
- snap together at contextual attachment points
- be sized to line up and interlock perfectly when snapped together
- have built in colliders
- be able to be batched or instanced to reduce draw calls

Tasks:
- [ ] Basic Kit Piece Library
- [ ] Build Contextual Attachment Point System
- [ ] Embed Colliders in Kit Pieces
- [ ] Re-Implement Batched Meshes from Kit Pieces
- [ ] Re-Implement Instanced Meshes from Kit Pieces

**Comment by HexaField** [comment]
- [ ] Grid snapping and alignment
- [ ] Object-aligned bounding boxes and object-space snapping
- [ ] AttachmentPointComponent for connecting objects together
- [ ] Combine interaction UXs (scene placement, teleport, studio interaction) deeper into spatial input with re-usable component
- [ ] Material Library
  - [ ] Handling materials as standalone assets
  - [ ] Thumbnail with a sphere like unity/unreal/blender etc
- [ ] Thumbnails for GLTF
- [ ] LOD autogen
