### ISSUE TITLE
[Epic]: Studio Refactor

### ISSUE THREAD

**Issue by dinomut1** [EtherealEngine/etherealengine#9276]
We need to rework the UI/UX in the studio to make it more flexible and modular.

- [ ] Replace `react-dock` with our own panel system

- [ ] Break down existing interface into modular panels categorized by context
- Transform buttons go into Transform Panel
- Snapping Panel
- Debug Panel
- Play Mode Options
- All existing panels are labeled:
- Properties
- Hierarchy / Scene Graph
- File Browser
- Assets

- [ ] Refactoring Properties Panel
- Make all component editors collapsible (minimize functionality)
- Possibly separate them into categorized tabs
- Embed Graph and Material editors into properties as node editors of their respective components

- [ ] Refactoring Component Shelf
- Remove it as a standalone panel
- Embed in properties panel as an "Add Component" button
- Functionality of default components is replaced with prefabs in the Assets Panel and File Browser
