### ISSUE TITLE
[Epic] Migrate from Threejs to Pure ECS

### ISSUE THREAD

**Issue by HexaField** [EtherealEngine/etherealengine#9308]
- [ ] Replace usage of `Engine.instance.scene.add` with entities
- [ ] Replace usage of `Object3D.add` with entities
- [ ] All debug helpers are their own entities
- [ ] Replace GroupComponent with MeshComponent
- [ ] Replace MeshComponent `geometry`, `material`, `morphTarget` with references to other entities with components for that data
- [ ] Add components for all threejs objects
- [ ] replace object layers with ObjectLayerComponent
- [ ] replace render order with RenderOrderComponent defaulting to 0 if no component
- [ ] Add SkinnedMeshComponent and BoneComponent and break avatars into entity hierarchy
- [ ] Implement animation mixer on ECS
- [ ] Add Light Components (base light, ambient, directional, hemisphere, point, spot, rect area)
- [ ] Replace Scene object with relevant state directly (fog, backgrund, environment)

reference
https://docs.google.com/spreadsheets/d/1-bSRrtmXdUhmqrqn1SaAU2muBPnxF9QLyCCAel9vbx0/edit#gid=0
