### ISSUE TITLE
[Epic]: Human readable aliaias for ECS names (UUIDs in ECS) & QOL updates to '`' debug view

### ISSUE THREAD

**Issue by mrhegemon** [EtherealEngine/etherealengine#9342]
## Stories

ECS
- [ ] add human readable name so UUID (eg "2c604975-3925-4717-9521-07df90481968") is a generated name of compounded properties (eg "entity-something.comp-media-1-2c604975-3925-4717-9521-07df90481968" or SOMETHING)

Debugger
- [ ] add debug button in editor, 
- [ ] make it show up in studio window?
- [ ] add pause?
- [ ] add command console?

- [ ]

**Comment by HexaField** [comment]
I've made non object component data show up nicely rather than being splayed into a key value array
