### ISSUE TITLE
[Epic]: Asset benchmark and alert system in the studio

### ISSUE THREAD

**Issue by mrhegemon** [EtherealEngine/etherealengine#9351]
## Stories

- [ ] Go to publish, the user is alerted when assets have too many polys/materials
   - [ ] Suggests to decimate, compress, and atlas
- [ ] Large assets in the hierarchy show a triangle alert when they are too large
  - [ ] tooltip suggest LODs, atlas, compression etc
