### ISSUE TITLE
[Epic]: Content Pipeline March Roadmap

### ISSUE THREAD

**Issue by dinomut1** [EtherealEngine/etherealengine#9420]
### Snap system
- [ ] Object space snapping 
- [ ] Physics collider based snapping 
### Assets Panel
- [ ] Project resource databases
- [ ] Assets Panel UI Element
- [ ] Thumbnail Handling
- [ ] Material Palette / Editing / Assignment Userflow
- - [ ] Saving materials into standalone files
- - [ ] Adding preview sphere to material editor
- - [ ] Drag and drop assignment of materials from standalone files
### File Browser
- [ ] Add icon view mode (see Studio Wireframe)
- [ ] Revamp list view
### LOD System
- [ ] Compression Panel (see Studio Wireframe)
- [ ] LOD presets
- [ ] Batched compression
- [ ] Automated variant prefab generation
- [ ] Import settings panel
### Studio UI
- [ ] Layout presets and saving custom layouts
- [ ] Removing components shelf on right, embedding into properties (+ button)
- [ ] Using Assets Panel for almost all scene comp
### Postprocessing
- [ ] Fix Postprocessing Component
- [ ] SDF Component <-> SDF Post Processing System MVP
